### ISSUE TITLE
bookings - lier les personnes inscrites à l'événement avec les adhérents via le mail

### ISSUE THREAD

**Issue by flutter-painter** [kd2org/paheko-modules#2]
Salut Paheko,

Votre outil est génial et complet ! Un grand bravo et merci pour votre démarche libre.

Je me permets d'ouvrir une issue concernant **les réservations** et le besoin spécifique de notre asso.
L'association laisse la possibilité à tout le monde de réserver pour l'événement à venir (adhérent ou pas, à jour de cotisation ou pas). Ceux qui doivent s'inscrire ou s'acquitter de leur cotisation le feront sur place le jour de l'événement.

Il est plus facile de préparer l'événement en identifiant ceux qui devront s'acquitter de la cotisation. 
Pour cela on va  :

1. exporter la liste des personnes inscrites à l'événement
2. exporter la liste des adhérents
3. left join les listes sur le champs mail
4. identifier les personnes inscrites qui ne sont pas adhérentes OU qui sont adhérentes mais pas à jour de leur cotisation
5. imprimer pour suivi papier lors de l'événement

Est-ce qu'il serait possible de proposer ce rapprochement automatiquement dans le module afin de ne pas avoir à faire cette manipulation ?

**Comment by bohwaz** [comment]
Je viens d'intégrer ça, merci, ça sera dans la 1.3.7.

D'autre part, le fait que les issues soient ouvertes sur ce repo était une erreur, nous n'utilisons pas Github, merci à l'avenir d'utiliser les moyens de communication du projet : https://fossil.kd2.org/paheko/wiki?name=Entraide
